# This file configures how Netlify builds and deploys your Flask application.

[build]
  # The command Netlify runs to install your Python dependencies.
  command = "pip install -r requirements.txt"

  # The directory Netlify should publish. For Flask apps, we point to the root.
  publish = "."

# Specifies the Python version for the build environment.
[build.environment]
  PYTHON_VERSION = "3.10" # Ensure this matches your local Python version

# --- Functions Configuration ---
# This tells Netlify where to find your serverless functions.
# Netlify will automatically detect Python functions by convention.
[functions]
  directory = "functions" # This is the folder where your server.py and __init__.py are.
  # No 'node_bundler' or explicit 'runtime' needed here, as Netlify auto-detects Python.

# --- Redirects ---
# This rule tells Netlify to send all incoming requests to your serverless function.
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server" # Points to the generated function named 'server'
  status = 200 # Indicate a successful proxy
