# This file configures how Netlify builds and deploys your Flask application.

[build]
  # The command Netlify runs to install your Python dependencies.
  # This assumes your requirements.txt is in the root of your repository.
  command = "pip install -r requirements.txt"

  # The directory Netlify should publish. For Flask apps, we typically
  # publish from the root directory, as Flask serves content dynamically.
  publish = "."

# Specifies the Python version for the build environment.
[build.environment]
  PYTHON_VERSION = "3.10" # Keep this matching your Python version.

# --- Crucial for Running Flask on Netlify ---
# This section tells Netlify's serverless functions environment (which is used
# to run Python apps like Flask) how to handle incoming HTTP requests.
# This essentially acts as a proxy that routes all requests to your Flask app.
# The 'external_node_modules' is often required for Python functions to work.
[functions]
  directory = "functions" # This directory can be empty or contain other serverless functions.
                          # Netlify will create it if it doesn't exist.

# --- Redirects to ensure all traffic goes through your Flask app ---
# This is the most common and robust way to deploy Flask on Netlify.
# It uses Netlify's rewrite rules to proxy all requests to your Flask app.
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server" # This points to the Netlify Function that runs your Flask app
  status = 200
