# This file configures how Netlify builds and deploys your Flask application.

[build]
  # The command Netlify runs to install your Python dependencies.
  # This assumes your requirements.txt is in the root of your repository.
  command = "pip install -r requirements.txt"

  # The directory Netlify should publish. For Flask apps, we typically
  # publish from the root directory, as Flask serves content dynamically.
  # This fixes the "deploy directory 'build' does not exist" error.
  publish = "."

# Specifies the Python version for the build environment.
# Choose a version compatible with your local development setup and your dependencies.
# Example: "3.9", "3.10", "3.11"
[build.environment]
  PYTHON_VERSION = "3.10"

# --- IMPORTANT: Redirects for Flask ---
# This section tells Netlify to send all web requests to your Flask application.
# Netlify will automatically detect Gunicorn (from requirements.txt) and run
# your Flask app instance (usually named 'app' in 'app.py').
# We are *removing* the explicit `to = "/app.py"` redirect that caused
# Netlify to serve the app.py code as a static file.
# By setting `from = "/*"` and `to = "/index.html"` (or any fallback if you have a landing page),
# Netlify will run your Flask app and let it handle all routing.
# However, for Flask, the simplest way is to *remove* explicit redirects
# and let Netlify's build system auto-detect and run Gunicorn/Flask.
# Therefore, NO [[redirects]] block is needed here for a typical Flask setup.
